//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeraFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeraFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000 {
            get {
                object obj = ResourceManager.GetObject("000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] den_locations {
            get {
                object obj = ResourceManager.GetObject("den_locations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] encounter_gem_paldea {
            get {
                object obj = ResourceManager.GetObject("encounter_gem_paldea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1862 {
            get {
                object obj = ResourceManager.GetObject("item_1862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1863 {
            get {
                object obj = ResourceManager.GetObject("item_1863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1864 {
            get {
                object obj = ResourceManager.GetObject("item_1864", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1865 {
            get {
                object obj = ResourceManager.GetObject("item_1865", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1866 {
            get {
                object obj = ResourceManager.GetObject("item_1866", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1867 {
            get {
                object obj = ResourceManager.GetObject("item_1867", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1868 {
            get {
                object obj = ResourceManager.GetObject("item_1868", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1869 {
            get {
                object obj = ResourceManager.GetObject("item_1869", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1870 {
            get {
                object obj = ResourceManager.GetObject("item_1870", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1871 {
            get {
                object obj = ResourceManager.GetObject("item_1871", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1872 {
            get {
                object obj = ResourceManager.GetObject("item_1872", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1873 {
            get {
                object obj = ResourceManager.GetObject("item_1873", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1874 {
            get {
                object obj = ResourceManager.GetObject("item_1874", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1875 {
            get {
                object obj = ResourceManager.GetObject("item_1875", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1876 {
            get {
                object obj = ResourceManager.GetObject("item_1876", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1877 {
            get {
                object obj = ResourceManager.GetObject("item_1877", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1878 {
            get {
                object obj = ResourceManager.GetObject("item_1878", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_1879 {
            get {
                object obj = ResourceManager.GetObject("item_1879", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///Plugin.OutbreakViewer=Mass Outbreak Viewer/Editor
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///Plugin.OutbreakViewer=Mass Outbreak Viewer/Editor
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Conectar a Dispositivo Remoto
        ///Plugin.TeraViewer=Visor/Editor de Teraincursiones
        ///Plugin.SeedChecker=Inspector de Seeds
        ///Plugin.FlagEditor=Edita Flags del Juego
        ///Plugin.NewsImporter=Importar Noticias Poképortal
        ///Plugin.OutbreakViewer=Mass Outbreak Viewer/Editor
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Herramientas
        ///TeraFinderForm.btnRemoteConnect=Conectar a Dispositivo Remoto
        ///TeraFinderForm.languageToolStr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///Plugin.OutbreakViewer=Mass Outbreak Viewer/Editor
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connetti a Dispositivo Remoto
        ///Plugin.TeraViewer=Visualizza e Modifica Raid
        ///Plugin.SeedChecker=Controlla Seed
        ///Plugin.FlagEditor=Modifica Flags di Gioco
        ///Plugin.NewsImporter=Importa Raid Evento
        ///Plugin.OutbreakViewer=Visualizza e Modifica Comparse Massicce
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Strumenti
        ///TeraFinderForm.btnRemoteConnect=Connetti a Dispositivo Remoto
        ///TeraFinderForm.languageToolStrip=Ling [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///Plugin.OutbreakViewer=Mass Outbreak Viewer/Editor
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=테라 파인더 플러그인
        ///Plugin.ConnectRemote=스위치에 연결
        ///Plugin.TeraViewer=레이드 보기/편집
        ///Plugin.SeedChecker=테라 레이드 시드체크
        ///Plugin.FlagEditor=게임 플래그 편집
        ///Plugin.NewsImporter=포켓포털 뉴스 불러오기
        ///Plugin.OutbreakViewer=대량발생 보기/편집
        ///
        ///TeraFinderForm=테라 파인더 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=도구
        ///TeraFinderForm.btnRemoteConnect=스위치에 연결
        ///TeraFinderForm.languageToolStrip=언어
        ///TeraFinderForm.grpSAV=세이브 파일
        ///TeraFinderForm.grpSavTools=세이브 툴
        ///TeraFinderForm.grpStaticTools=독립 툴
        ///TeraFinderForm.grpTools=테라 파인더 도구 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=太晶洞窟搜索插件
        ///Plugin.ConnectRemote=远程连接
        ///Plugin.TeraViewer=太晶洞窟查看/编辑
        ///Plugin.SeedChecker=太晶洞窟Seed检索
        ///Plugin.FlagEditor=编辑太晶洞窟解锁进度
        ///Plugin.NewsImporter=导入宝可梦入口站新闻
        ///Plugin.OutbreakViewer=大量出现查看/编辑
        ///
        ///TeraFinderForm=太晶洞窟搜索
        ///TeraFinderForm.remoteConnectToolStripMenuItem=工具
        ///TeraFinderForm.btnRemoteConnect=远程连接
        ///TeraFinderForm.languageToolStrip=语言设置
        ///TeraFinderForm.grpSAV=存档文件
        ///TeraFinderForm.grpSavTools=存档工具
        ///TeraFinderForm.grpStaticTools=独立工具
        ///TeraFinderForm.grpTools=工具
        ///TeraFinderForm.btnL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=太晶洞窟搜索插件
        ///Plugin.ConnectRemote=遠程連接
        ///Plugin.TeraViewer=太晶洞窟查看/編輯
        ///Plugin.SeedChecker=太晶洞窟Seed檢索
        ///Plugin.FlagEditor=編輯太晶洞窟解鎖進度
        ///Plugin.NewsImporter=導入寶可夢入口站新聞
        ///Plugin.OutbreakViewer=大量出現查看/編輯
        ///
        ///TeraFinderForm=太晶洞窟搜索
        ///TeraFinderForm.remoteConnectToolStripMenuItem=工具
        ///TeraFinderForm.btnRemoteConnect=遠程連接
        ///TeraFinderForm.languageToolStrip=語言設置
        ///TeraFinderForm.grpSAV=储存资料文件
        ///TeraFinderForm.grpSavTools=储存资料工具
        ///TeraFinderForm.grpStaticTools=獨立工具
        ///TeraFinderForm.grpTools=工具
        ///TeraFinderForm. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh2 {
            get {
                return ResourceManager.GetString("lang_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] raid_fixed_reward_item_array {
            get {
                object obj = ResourceManager.GetObject("raid_fixed_reward_item_array", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] raid_lottery_reward_item_array {
            get {
                object obj = ResourceManager.GetObject("raid_lottery_reward_item_array", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap world {
            get {
                object obj = ResourceManager.GetObject("world", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
