name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to latest version for security

    - name: Set up .NET
      uses: actions/setup-dotnet@v4  # Update to latest version
      with:
        dotnet-version: '9.0.x'  # Use .NET 9.0 SDK
        dotnet-quality: 'preview'  # Optional: for preview releases

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Debug --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
